name = "db-site-worker"
account_id = "fa227777c8b69f6569d4a4347a6cceb8"
workers_dev = true
compatibility_date = "2024-06-01"
main = "./src/index.ts"
kv_namespaces = [
    { binding = "atlas_api_cache", preview_id = "ea0f171f5e2544709dfccc02701a9e51", id = "6307c816b0714a5e8fc7ce5f9f58226f" },
]

[site]
bucket = "../../app"
