name: Cloudflare Worker Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Build sites
        shell: bash
        run: |
          sudo apt-get install -y moreutils
          bash netlify_build.sh | ts -s '(%M:%.S)]' | ts '[%.T'
      - name: Install worker dependencies
        working-directory: 'packages/db-og-worker'
        run: npm ci
      - name: Publish to Cloudflare Worker
        working-directory: 'packages/db-og-worker'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npx wrangler deploy
